sudo: required
services:
    - docker
install:
    - curl -L https://raw.githubusercontent.com/experimental-platform/build-scripts/master/go-build.sh | bash
script:
    - curl -L https://raw.githubusercontent.com/experimental-platform/build-scripts/master/buildimg.sh | bash
